### ISSUE TITLE
Current version of tdl-local-sqs only listens at a fixed port 9324

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/tdl-local-sqs#2]
While embedding `tdl-local-sqs` into `tdl-client-java` I realised that the current version does not accept a custom port and always listens at 9324.  Its okay to have a default port but would be good to also supply a custom one, in case the default one is not available.

This did cause manual work when trying to make it work with `tdl-client-java`, as its config looks for a specific port 28161, of course, we can change that but then to avoid more changes I rather our supporting programs can be run with custom params.

**Comment by neomatrix369** [comment]
I'll try to throw a PR with some enhancement at it.

**Comment by julianghionoiu** [comment]
The `tdl-local-sqs` should be as simple as importing a module. If we also have to configure it then it becomes harder to use. We should use convention rather than configuration, so it is ok to listen on 9324

The `tdl-client-java` already has support for changing the port.

**Comment by neomatrix369** [comment]
It's a bit of a change on that end as well - it's now how I found it, I have seen port numbers hardcoded in the source, let me give it a whirl and report back, just want to avoid fixing cascades of them. Was it written that way to follow a fixed port convention?

**Comment by neomatrix369** [comment]
Closing this issue after applying changes to the SQS implementation of the `tdl-client-java` project. Small changes were made to port number across a few files. Test config had the port number hard-coded, although config file for production makes it easier to change port number
